apiVersion: cos.tencentcloud.crossplane.io/v1alpha1
kind: BucketDomainCertificateAttachment
metadata:
  annotations:
    meta.upbound.io/example-id: cos/v1alpha1/bucketdomaincertificateattachment
  labels:
    testing.upbound.io/example-name: example
  name: example
spec:
  forProvider:
    bucketSelector:
      matchLabels:
        testing.upbound.io/example-name: example
    domainCertificate:
    - certificate:
      - certType: CustomCert
        customCert:
        - cert: '-----BEGIN CERTIFICATE-----'
          certId: Mbx45wts
          privateKey: '-----BEGIN RSA PRIVATE_KEY-----'
      domain: www.example.com

---

apiVersion: cos.tencentcloud.crossplane.io/v1alpha1
kind: Bucket
metadata:
  annotations:
    meta.upbound.io/example-id: cos/v1alpha1/bucketdomaincertificateattachment
  labels:
    testing.upbound.io/example-name: example
  name: example
spec:
  forProvider:
    acl: private
    bucket: private-bucket-${local.app_id}
    forceClean: true
