apiVersion: cos.tencentcloud.crossplane.io/v1alpha1
kind: BucketPolicy
metadata:
  annotations:
    meta.upbound.io/example-id: cos/v1alpha1/bucketpolicy
  labels:
    testing.upbound.io/example-name: example
  name: example
spec:
  forProvider:
    bucketSelector:
      matchLabels:
        testing.upbound.io/example-name: example
    policy: |
      {
        "version": "2.0",
        "Statement": [
          {
            "Principal": {
              "qcs": [
                "qcs::cam::uin/<your-account-id>:uin/<your-account-id>"
              ]
            },
            "Action": [
              "name/cos:DeleteBucket",
              "name/cos:PutBucketACL"
            ],
            "Effect": "allow",
            "Resource": [
              "qcs::cos:<bucket region>:uid/<your-appid-id>:<your-bucket-name>/*"
            ]
          }
        ]
      }

---

apiVersion: cos.tencentcloud.crossplane.io/v1alpha1
kind: Bucket
metadata:
  annotations:
    meta.upbound.io/example-id: cos/v1alpha1/bucketpolicy
  labels:
    testing.upbound.io/example-name: example
  name: example
spec:
  forProvider:
    acl: private
    bucket: private-bucket-${local.app_id}
