apiVersion: clb.tencentcloud.crossplane.io/v1alpha1
kind: CustomizedConfig
metadata:
  annotations:
    meta.upbound.io/example-id: clb/v1alpha1/customizedconfig
  labels:
    testing.upbound.io/example-name: example
  name: example
spec:
  forProvider:
    configContent: "client_max_body_size 224M;\r\nclient_body_timeout 60s;"
    configName: tf-example
