apiVersion: clb.tencentcloud.crossplane.io/v1alpha1
kind: TargetGroupAttachment
metadata:
  annotations:
    meta.upbound.io/example-id: clb/v1alpha1/targetgroupattachment
  labels:
    testing.upbound.io/example-name: example
  name: example
spec:
  forProvider:
    clbIdSelector:
      matchLabels:
        testing.upbound.io/example-name: example
    listenerIdSelector:
      matchLabels:
        testing.upbound.io/example-name: example
    ruleIdSelector:
      matchLabels:
        testing.upbound.io/example-name: example
    targetGroupIdSelector:
      matchLabels:
        testing.upbound.io/example-name: example

---

apiVersion: clb.tencentcloud.crossplane.io/v1alpha1
kind: Instance
metadata:
  annotations:
    meta.upbound.io/example-id: clb/v1alpha1/targetgroupattachment
  labels:
    testing.upbound.io/example-name: example
  name: example
spec:
  forProvider:
    clbName: tf-example
    networkType: INTERNAL
    subnetIdSelector:
      matchLabels:
        testing.upbound.io/example-name: subnet
    vpcIdSelector:
      matchLabels:
        testing.upbound.io/example-name: vpc

---

apiVersion: clb.tencentcloud.crossplane.io/v1alpha1
kind: Listener
metadata:
  annotations:
    meta.upbound.io/example-id: clb/v1alpha1/targetgroupattachment
  labels:
    testing.upbound.io/example-name: example
  name: example
spec:
  forProvider:
    clbIdSelector:
      matchLabels:
        testing.upbound.io/example-name: example
    listenerName: tf-example
    port: 8080
    protocol: HTTP

---

apiVersion: clb.tencentcloud.crossplane.io/v1alpha1
kind: ListenerRule
metadata:
  annotations:
    meta.upbound.io/example-id: clb/v1alpha1/targetgroupattachment
  labels:
    testing.upbound.io/example-name: example
  name: example
spec:
  forProvider:
    clbIdSelector:
      matchLabels:
        testing.upbound.io/example-name: example
    domain: example.com
    listenerIdSelector:
      matchLabels:
        testing.upbound.io/example-name: example
    scheduler: WRR
    sessionExpireTime: 60
    targetType: TARGETGROUP
    url: /

---

apiVersion: clb.tencentcloud.crossplane.io/v1alpha1
kind: TargetGroup
metadata:
  annotations:
    meta.upbound.io/example-id: clb/v1alpha1/targetgroupattachment
  labels:
    testing.upbound.io/example-name: example
  name: example
spec:
  forProvider:
    targetGroupName: tf-example
    vpcId: ${tencentcloud_vpc.vpc.id}

---

apiVersion: vpc.tencentcloud.crossplane.io/v1alpha1
kind: Subnet
metadata:
  annotations:
    meta.upbound.io/example-id: clb/v1alpha1/targetgroupattachment
  labels:
    testing.upbound.io/example-name: subnet
  name: subnet
spec:
  forProvider:
    availabilityZone: ${var.availability_zone}
    cidrBlock: 10.0.1.0/24
    isMulticast: false
    name: subnet
    vpcIdSelector:
      matchLabels:
        testing.upbound.io/example-name: vpc

---

apiVersion: vpc.tencentcloud.crossplane.io/v1alpha1
kind: VPC
metadata:
  annotations:
    meta.upbound.io/example-id: clb/v1alpha1/targetgroupattachment
  labels:
    testing.upbound.io/example-name: vpc
  name: vpc
spec:
  forProvider:
    cidrBlock: 10.0.0.0/16
    name: vpc
