apiVersion: clb.tencentcloud.crossplane.io/v1alpha1
kind: TargetGroupInstanceAttachment
metadata:
  annotations:
    meta.upbound.io/example-id: clb/v1alpha1/targetgroupinstanceattachment
  labels:
    testing.upbound.io/example-name: example
  name: example
spec:
  forProvider:
    bindIp: ${data.tencentcloud_instances.instances.instance_list[0].private_ip}
    port: 8080
    targetGroupIdSelector:
      matchLabels:
        testing.upbound.io/example-name: example
    weight: 10

---

apiVersion: clb.tencentcloud.crossplane.io/v1alpha1
kind: TargetGroup
metadata:
  annotations:
    meta.upbound.io/example-id: clb/v1alpha1/targetgroupinstanceattachment
  labels:
    testing.upbound.io/example-name: example
  name: example
spec:
  forProvider:
    targetGroupName: tf-example
    vpcId: ${tencentcloud_vpc.vpc.id}

---

apiVersion: cvm.tencentcloud.crossplane.io/v1alpha1
kind: Instance
metadata:
  annotations:
    meta.upbound.io/example-id: clb/v1alpha1/targetgroupinstanceattachment
  labels:
    testing.upbound.io/example-name: example
  name: example
spec:
  forProvider:
    availabilityZone: ${data.tencentcloud_availability_zones.default.zones.0.name}
    dataDisks:
    - dataDiskSize: 50
      dataDiskType: CLOUD_PREMIUM
      encrypt: false
    hostname: user
    imageId: ${data.tencentcloud_images.images.images.0.image_id}
    instanceName: tf-example
    instanceType: ${data.tencentcloud_instance_types.instance_types.instance_types.0.instance_type}
    internetMaxBandwidthOut: 100
    projectId: 0
    subnetIdSelector:
      matchLabels:
        testing.upbound.io/example-name: subnet
    systemDiskSize: 50
    systemDiskType: CLOUD_PREMIUM
    tags:
      tagKey: tagValue
    vpcIdSelector:
      matchLabels:
        testing.upbound.io/example-name: vpc

---

apiVersion: vpc.tencentcloud.crossplane.io/v1alpha1
kind: Subnet
metadata:
  annotations:
    meta.upbound.io/example-id: clb/v1alpha1/targetgroupinstanceattachment
  labels:
    testing.upbound.io/example-name: subnet
  name: subnet
spec:
  forProvider:
    availabilityZone: ${data.tencentcloud_availability_zones.default.zones.0.name}
    cidrBlock: 10.0.1.0/24
    name: subnet
    vpcIdSelector:
      matchLabels:
        testing.upbound.io/example-name: vpc

---

apiVersion: vpc.tencentcloud.crossplane.io/v1alpha1
kind: VPC
metadata:
  annotations:
    meta.upbound.io/example-id: clb/v1alpha1/targetgroupinstanceattachment
  labels:
    testing.upbound.io/example-name: vpc
  name: vpc
spec:
  forProvider:
    cidrBlock: 10.0.0.0/16
    name: vpc
