apiVersion: tke.tencentcloud.crossplane.io/v1alpha1
kind: ClusterEndpoint
metadata:
  annotations:
    meta.upbound.io/example-id: tke/v1alpha1/clusterendpoint
  labels:
    testing.upbound.io/example-name: example
  name: example
spec:
  forProvider:
    clusterIdSelector:
      matchLabels:
        testing.upbound.io/example-name: example
    clusterIntranet: true
    clusterIntranetDomain: intranet_demo.com
    clusterIntranetSubnetIdSelector:
      matchLabels:
        testing.upbound.io/example-name: example
