apiVersion: kafka.tencentcloud.crossplane.io/v1alpha1
kind: Topic
metadata:
  annotations:
    meta.upbound.io/example-id: kafka/v1alpha1/topic
  labels:
    testing.upbound.io/example-name: example
  name: example
spec:
  forProvider:
    cleanUpPolicy: delete
    enableWhiteList: true
    instanceIdSelector:
      matchLabels:
        testing.upbound.io/example-name: example
    ipWhiteList:
    - 1.1.1.1
    - 2.2.2.2
    maxMessageBytes: 4096
    note: topic note
    partitionNum: 2
    replicaNum: 4
    retention: 60000
    segment: 86400000
    syncReplicaMinNum: 2
    topicName: tf-example
    uncleanLeaderElectionEnable: false
