apiVersion: monitor.tencentcloud.crossplane.io/v1alpha1
kind: TmpExporterIntegration
metadata:
  annotations:
    meta.upbound.io/example-id: monitor/v1alpha1/tmpexporterintegration
  labels:
    testing.upbound.io/example-name: example
  name: example
spec:
  forProvider:
    clusterId: cls-csxm4phu
    content: '{"name":"test","kind":"qcloud-exporter","spec":{"scrapeSpec":{"interval":"1m","timeout":"1m","relabelConfigs":"#metricRelabelings:\n#-
      action: labeldrop\n#  regex: tmp_test_label\n"},"instanceSpec":{"region":"Guangzhou","role":"CM_QCSLinkedRoleInTMP","useRole":true,"authProvider":{"method":1,"presetRole":"CM_QCSLinkedRoleInTMP"},"rateLimit":1000,"delaySeconds":0,"rangeSeconds":0,"reload_interval_minutes":10,"uin":"100023201586","tag_key_operation":"ToUnderLineAndLower"},"exporterSpec":{"cvm":false,"cbs":true,"imageRegistry":"ccr.ccs.tencentyun.com","cpu":"0.25","memory":"0.5Gi"}},"status":{}}'
    instanceIdSelector:
      matchLabels:
        testing.upbound.io/example-name: example
    kind: qcloud-exporter
    kubeType: 3
