apiVersion: cam.tencentcloud.crossplane.io/v1alpha1
kind: GroupMembership
metadata:
  annotations:
    meta.upbound.io/example-id: cam/v1alpha1/groupmembership
  labels:
    testing.upbound.io/example-name: example
  name: example
spec:
  forProvider:
    groupIdSelector:
      matchLabels:
        testing.upbound.io/example-name: example
    userNames:
    - ${tencentcloud_cam_user.example.id}

---

apiVersion: cam.tencentcloud.crossplane.io/v1alpha1
kind: Group
metadata:
  annotations:
    meta.upbound.io/example-id: cam/v1alpha1/groupmembership
  labels:
    testing.upbound.io/example-name: example
  name: example
spec:
  forProvider:
    name: tf-example
    remark: remark.

---

apiVersion: cam.tencentcloud.crossplane.io/v1alpha1
kind: User
metadata:
  annotations:
    meta.upbound.io/example-id: cam/v1alpha1/groupmembership
  labels:
    testing.upbound.io/example-name: example
  name: example
spec:
  forProvider:
    consoleLogin: true
    countryCode: "86"
    email: example@tencent.com
    forceDelete: true
    name: tf-example
    needResetPassword: true
    passwordSecretRef:
      key: example-key
      name: example-secret
      namespace: upbound-system
    phoneNum: "18611111111"
    remark: remark.
    tags:
      createBy: Terraform
    useApi: true
