apiVersion: cam.tencentcloud.crossplane.io/v1alpha1
kind: User
metadata:
  annotations:
    meta.upbound.io/example-id: cam/v1alpha1/user
  labels:
    testing.upbound.io/example-name: example
  name: example
spec:
  forProvider:
    consoleLogin: true
    countryCode: "86"
    email: example@qq.com
    forceDelete: true
    name: tf-example
    needResetPassword: true
    passwordSecretRef:
      key: example-key
      name: example-secret
      namespace: upbound-system
    phoneNum: 189********
    remark: Remark.
    tags:
      createBy: Terraform
    useApi: true
