/*
Copyright 2022 Upbound Inc.
*/

// Code generated by upjet. DO NOT EDIT.

package v1alpha1

// Hub marks this type as a conversion hub.
func (tr *Queue) Hub() {}

// Hub marks this type as a conversion hub.
func (tr *Subscribe) Hub() {}

// Hub marks this type as a conversion hub.
func (tr *Topic) Hub() {}
