apiVersion: dc.tencentcloud.crossplane.io/v1alpha1
kind: Gateway
metadata:
  annotations:
    meta.upbound.io/example-id: dc/v1alpha1/gateway
  labels:
    testing.upbound.io/example-name: example
  name: example
spec:
  forProvider:
    gatewayType: NORMAL
    name: tf-example
    networkInstanceId: ${tencentcloud_vpc.vpc.id}
    networkType: VPC

---

apiVersion: vpc.tencentcloud.crossplane.io/v1alpha1
kind: VPC
metadata:
  annotations:
    meta.upbound.io/example-id: dc/v1alpha1/gateway
  labels:
    testing.upbound.io/example-name: vpc
  name: vpc
spec:
  forProvider:
    cidrBlock: 10.0.0.0/16
    name: vpc
