apiVersion: postgresql.tencentcloud.crossplane.io/v1alpha1
kind: Instance
metadata:
  annotations:
    meta.upbound.io/example-id: postgresql/v1alpha1/instance
  labels:
    testing.upbound.io/example-name: example
  name: example
spec:
  forProvider:
    availabilityZone: ${var.availability_zone}
    chargeType: POSTPAID_BY_HOUR
    charset: UTF8
    cpu: 1
    dbMajorVersion: "10"
    engineVersion: "10.23"
    memory: 2
    name: example
    projectId: 0
    rootPasswordSecretRef:
      key: example-key
      name: example-secret
      namespace: upbound-system
    rootUser: root123
    storage: 10
    subnetIdSelector:
      matchLabels:
        testing.upbound.io/example-name: subnet
    tags:
      CreateBy: Terraform
    vpcIdSelector:
      matchLabels:
        testing.upbound.io/example-name: vpc

---

apiVersion: vpc.tencentcloud.crossplane.io/v1alpha1
kind: Subnet
metadata:
  annotations:
    meta.upbound.io/example-id: postgresql/v1alpha1/instance
  labels:
    testing.upbound.io/example-name: subnet
  name: subnet
spec:
  forProvider:
    availabilityZone: ${var.availability_zone}
    cidrBlock: 10.0.20.0/28
    isMulticast: false
    name: subnet
    vpcIdSelector:
      matchLabels:
        testing.upbound.io/example-name: vpc

---

apiVersion: vpc.tencentcloud.crossplane.io/v1alpha1
kind: VPC
metadata:
  annotations:
    meta.upbound.io/example-id: postgresql/v1alpha1/instance
  labels:
    testing.upbound.io/example-name: vpc
  name: vpc
spec:
  forProvider:
    cidrBlock: 10.0.0.0/16
    name: vpc
