apiVersion: cvm.tencentcloud.crossplane.io/v1alpha1
kind: Instance
metadata:
  name: example-cvm
spec:
  forProvider:
    instanceName: "test-crossplane-cvm"
    availabilityZone: "ap-guangzhou-3"
    imageId: "img-9qrfy1xt"
    instanceType: "S5.MEDIUM2"
    systemDiskType: "CLOUD_PREMIUM"
    vpcidRef: 
      name: "example-cvm-vpc"
    subnetIdRef: 
      name: "example-cvm-subnet"