apiVersion: cynosdb.tencentcloud.crossplane.io/v1alpha1
kind: Cluster
metadata:
  annotations:
    meta.upbound.io/example-id: cynosdb/v1alpha1/cluster
  labels:
    testing.upbound.io/example-name: example
  name: example
spec:
  forProvider:
    availableZone: ${var.availability_zone}
    clusterName: tf-example
    dbMode: NORMAL
    dbType: MYSQL
    dbVersion: "5.7"
    forceDelete: false
    instanceCpuCore: 2
    instanceInitInfos:
    - cpu: 2
      deviceType: common
      instanceCount: 1
      instanceType: rw
      memory: 4
    - cpu: 2
      deviceType: exclusive
      instanceCount: 1
      instanceType: ro
      memory: 4
    instanceMaintainDuration: 7200
    instanceMaintainStartTime: 10800
    instanceMaintainWeekdays:
    - Fri
    - Mon
    - Sat
    - Sun
    - Thu
    - Wed
    - Tue
    instanceMemorySize: 4
    paramItems:
    - currentValue: utf8mb4
      name: character_set_server
    - currentValue: "0"
      name: lower_case_table_names
    passwordSecretRef:
      key: example-key
      name: example-secret
      namespace: upbound-system
    port: 3306
    roGroupSg:
    - ${tencentcloud_security_group.example.id}
    rwGroupSg:
    - ${tencentcloud_security_group.example.id}
    subnetIdSelector:
      matchLabels:
        testing.upbound.io/example-name: subnet
    tags:
      createBy: terraform
    vpcIdSelector:
      matchLabels:
        testing.upbound.io/example-name: vpc

---

apiVersion: vpc.tencentcloud.crossplane.io/v1alpha1
kind: SecurityGroup
metadata:
  annotations:
    meta.upbound.io/example-id: cynosdb/v1alpha1/cluster
  labels:
    testing.upbound.io/example-name: example
  name: example
spec:
  forProvider:
    description: sg desc.
    name: tf-example
    projectId: 0
    tags:
      example: test

---

apiVersion: vpc.tencentcloud.crossplane.io/v1alpha1
kind: Subnet
metadata:
  annotations:
    meta.upbound.io/example-id: cynosdb/v1alpha1/cluster
  labels:
    testing.upbound.io/example-name: subnet
  name: subnet
spec:
  forProvider:
    availabilityZone: ${var.availability_zone}
    cidrBlock: 10.0.20.0/28
    isMulticast: false
    name: subnet
    vpcIdSelector:
      matchLabels:
        testing.upbound.io/example-name: vpc

---

apiVersion: vpc.tencentcloud.crossplane.io/v1alpha1
kind: VPC
metadata:
  annotations:
    meta.upbound.io/example-id: cynosdb/v1alpha1/cluster
  labels:
    testing.upbound.io/example-name: vpc
  name: vpc
spec:
  forProvider:
    cidrBlock: 10.0.0.0/16
    name: vpc
