apiVersion: sqlserver.tencentcloud.crossplane.io/v1alpha1
kind: ReadonlyInstance
metadata:
  annotations:
    meta.upbound.io/example-id: sqlserver/v1alpha1/readonlyinstance
  labels:
    testing.upbound.io/example-name: example
  name: example
spec:
  forProvider:
    availabilityZone: ${data.tencentcloud_availability_zones_by_product.zones.zones.4.name}
    chargeType: POSTPAID_BY_HOUR
    forceUpgrade: true
    masterInstanceIdSelector:
      matchLabels:
        testing.upbound.io/example-name: example
    memory: 4
    name: tf_example
    readonlyGroupType: 1
    storage: 20
    subnetIdSelector:
      matchLabels:
        testing.upbound.io/example-name: subnet
    tags:
      CreateBy: Terraform
    vpcIdSelector:
      matchLabels:
        testing.upbound.io/example-name: vpc

---

apiVersion: vpc.tencentcloud.crossplane.io/v1alpha1
kind: SecurityGroup
metadata:
  annotations:
    meta.upbound.io/example-id: sqlserver/v1alpha1/readonlyinstance
  labels:
    testing.upbound.io/example-name: security_group
  name: security-group
spec:
  forProvider:
    description: desc.
    name: sg-example

---

apiVersion: sqlserver.tencentcloud.crossplane.io/v1alpha1
kind: Instance
metadata:
  annotations:
    meta.upbound.io/example-id: sqlserver/v1alpha1/readonlyinstance
  labels:
    testing.upbound.io/example-name: example
  name: example
spec:
  forProvider:
    availabilityZone: ${data.tencentcloud_availability_zones_by_product.zones.zones.4.name}
    chargeType: POSTPAID_BY_HOUR
    engineVersion: "2019"
    memory: 16
    multiZones: true
    name: tf-example
    projectId: 0
    securityGroups:
    - ${tencentcloud_security_group.security_group.id}
    storage: 20
    subnetIdSelector:
      matchLabels:
        testing.upbound.io/example-name: subnet
    vpcIdSelector:
      matchLabels:
        testing.upbound.io/example-name: vpc

---

apiVersion: vpc.tencentcloud.crossplane.io/v1alpha1
kind: Subnet
metadata:
  annotations:
    meta.upbound.io/example-id: sqlserver/v1alpha1/readonlyinstance
  labels:
    testing.upbound.io/example-name: subnet
  name: subnet
spec:
  forProvider:
    availabilityZone: ${data.tencentcloud_availability_zones_by_product.zones.zones.4.name}
    cidrBlock: 10.0.0.0/16
    isMulticast: false
    name: subnet-example
    vpcIdSelector:
      matchLabels:
        testing.upbound.io/example-name: vpc

---

apiVersion: vpc.tencentcloud.crossplane.io/v1alpha1
kind: VPC
metadata:
  annotations:
    meta.upbound.io/example-id: sqlserver/v1alpha1/readonlyinstance
  labels:
    testing.upbound.io/example-name: vpc
  name: vpc
spec:
  forProvider:
    cidrBlock: 10.0.0.0/16
    name: vpc-example
