apiVersion: cls.tencentcloud.crossplane.io/v1alpha1
kind: CosShipper
metadata:
  annotations:
    meta.upbound.io/example-id: cls/v1alpha1/cosshipper
  labels:
    testing.upbound.io/example-name: example
  name: example
spec:
  forProvider:
    bucket: ${tencentcloud_cos_bucket.example.id}
    compress:
    - format: lzop
    content:
    - format: json
      json:
      - enableTag: true
        metaFields:
        - __FILENAME__
        - __SOURCE__
        - __TIMESTAMP__
    interval: 300
    maxSize: 200
    partition: /%Y/%m/%d/%H/
    prefix: ap-guangzhou-fffsasad-1649734752
    shipperName: ap-guangzhou-fffsasad-1649734752
    topicIdSelector:
      matchLabels:
        testing.upbound.io/example-name: example

---

apiVersion: cls.tencentcloud.crossplane.io/v1alpha1
kind: Logset
metadata:
  annotations:
    meta.upbound.io/example-id: cls/v1alpha1/cosshipper
  labels:
    testing.upbound.io/example-name: example
  name: example
spec:
  forProvider:
    logsetName: tf-example
    tags:
      createBy: Terraform

---

apiVersion: cls.tencentcloud.crossplane.io/v1alpha1
kind: Topic
metadata:
  annotations:
    meta.upbound.io/example-id: cls/v1alpha1/cosshipper
  labels:
    testing.upbound.io/example-name: example
  name: example
spec:
  forProvider:
    autoSplit: false
    logsetIdSelector:
      matchLabels:
        testing.upbound.io/example-name: example
    maxSplitPartitions: 20
    partitionCount: 1
    period: 10
    storageType: hot
    tags:
      createBy: Terraform
    topicName: tf-example

---

apiVersion: cos.tencentcloud.crossplane.io/v1alpha1
kind: Bucket
metadata:
  annotations:
    meta.upbound.io/example-id: cls/v1alpha1/cosshipper
  labels:
    testing.upbound.io/example-name: example
  name: example
spec:
  forProvider:
    acl: private
    bucket: private-bucket-${local.app_id}
