apiVersion: cls.tencentcloud.crossplane.io/v1alpha1
kind: Logset
metadata:
  annotations:
    meta.upbound.io/example-id: cls/v1alpha1/logset
  labels:
    testing.upbound.io/example-name: example
  name: example
spec:
  forProvider:
    logsetName: tf-example
    tags:
      createdBy: Terraform
