apiVersion: cbs.tencentcloud.crossplane.io/v1alpha1
kind: Snapshot
metadata:
  annotations:
    meta.upbound.io/example-id: cbs/v1alpha1/snapshot
  labels:
    testing.upbound.io/example-name: example
  name: example
spec:
  forProvider:
    snapshotName: tf-example
    storageIdSelector:
      matchLabels:
        testing.upbound.io/example-name: example
    tags:
      createBy: Terraform
