apiVersion: vpc.tencentcloud.crossplane.io/v1alpha1
kind: RouteTableEntry
metadata:
  annotations:
    meta.upbound.io/example-id: vpc/v1alpha1/routetableentry
  labels:
    testing.upbound.io/example-name: example
  name: example
spec:
  forProvider:
    description: Terraform test.
    destinationCidrBlock: 10.12.12.0/24
    nextHub: "0"
    nextType: EIP
    routeTableIdSelector:
      matchLabels:
        testing.upbound.io/example-name: example

---

apiVersion: vpc.tencentcloud.crossplane.io/v1alpha1
kind: RouteTable
metadata:
  annotations:
    meta.upbound.io/example-id: vpc/v1alpha1/routetableentry
  labels:
    testing.upbound.io/example-name: example
  name: example
spec:
  forProvider:
    name: tf-example
    vpcIdSelector:
      matchLabels:
        testing.upbound.io/example-name: vpc

---

apiVersion: vpc.tencentcloud.crossplane.io/v1alpha1
kind: Subnet
metadata:
  annotations:
    meta.upbound.io/example-id: vpc/v1alpha1/routetableentry
  labels:
    testing.upbound.io/example-name: subnet
  name: subnet
spec:
  forProvider:
    availabilityZone: ${var.availability_zone}
    cidrBlock: 10.0.12.0/24
    name: subnet
    routeTableId: ${tencentcloud_route_table.example.id}
    vpcIdSelector:
      matchLabels:
        testing.upbound.io/example-name: vpc

---

apiVersion: vpc.tencentcloud.crossplane.io/v1alpha1
kind: VPC
metadata:
  annotations:
    meta.upbound.io/example-id: vpc/v1alpha1/routetableentry
  labels:
    testing.upbound.io/example-name: vpc
  name: vpc
spec:
  forProvider:
    cidrBlock: 10.0.0.0/16
    name: vpc
